src/engine/World.cpp

This does not compile on Clang/OS X. Could be perhaps fixed by including <ctype.h>, but it is probably better idea to use the C++-standard function instead of the obsolete one from POSIX.
Also fixes unrelated UB, related to assigning characters after the end of the string.

Fix usage of _tolower in WorldInstance::getBasicGameType

---

src/engine/Input.h
src/target/REGoth.cpp
src/utils/Utils.cpp
src/utils/Utils.h

Added smart delay which reveals itself when holding (rather than triggering) a button in menus (dialog, main..). This imitates the behavior of menu navigation in the original game, although the introduced delays may require adjustment to better reflect original Gothic's experience.

Added smart delay in menu navigation

---

src/logic/scriptExternals/Stubs.cpp

I regenerated all the stubs and added the ones missing from the code base. The previous ones didn't handle parameters of type c_item and func and something else (I don't have access to my script ATM). The new stubs also log the function names when called and verbose mode is on.
I haven't checked for duplicates in the implemented functions yet, will do when I'm on the machine with the generation script on it.

Replaced / added stubs

---

src/logic/PlayerController.cpp
src/ui/Hud.h

Prevent multiple menus of the same type being stacked on top of each other (fixes having to close ESC multiple times)
Toggle status screen when pressing 'B'

Menu stacking and status screen toggle

---

src/target/REGoth.cpp

Added a CLI option that enables vertical sync which limits FPS to 60 and reduces pressure on the video card when running REGoth.

Add CLI flag enabling vsync

---

src/logic/DialogManager.cpp
src/logic/DialogManager.h
src/logic/PlayerController.cpp
src/ui/Hud.cpp

I tried to read through the code-base a bit and fix some tiny issues along the way.
- pressing ESC in the main-menu was closing the menu but instantly spawning a new main-menu right after - now it only closes the existing menu
- regardless which option in a dialogue was highlighted, ESC would instantly end the dialogue
- menus can no longer be opened during a dialogue
- use ESC instead of Ctrl to advance a dialogue
I have a few questions regarding my changes though:
- Did Ctrl & ESC advance the dialog in vanilla gothic? As far as I can remember only ESC was used to jump through dialogues quickly
- will displaySubtitle() and stopDisplaySubtitle() also be called as soon as there is an option to disable subtitles in the game and will the setting be handled inside these functions? If not I …

Small fixes

---

src/logic/PlayerController.cpp
src/target/REGoth.cpp
src/ui/Hud.cpp

Every key was triggering UI::IA_Up. This means every key could be used to move up the choices in a dialogue-box.
Also the stat-screen could be shown even during dialogues.

More small fixes

---

src/content/Sky.cpp
src/engine/BaseEngine.cpp
src/engine/Input.cpp
src/logic/SavegameManager.cpp
src/target/REGoth.cpp
src/utils/Utils.cpp
src/utils/Utils.h
src/utils/cli.cpp
src/utils/cli.h
src/utils/zTools.cpp

Cli-flags can now be written to a config file. Currently, specifying an option on the CL has higher priority than the one in the config-file. 
If you want a flag to appear inside the config-file, you need to specify a default value and the regarding config-section. These have been added to the constructor of `Cli::Flag`.
Config-files are saved with the current settings from the CL-args at the end of `main`, so, when you close the game manually.

Configfiles

---

src/logic/PlayerController.cpp

Status menu will now open only if there is no active menu.

Fix status screen getting on top of other menus

---

src/logic/PlayerController.h
src/logic/ScriptEngine.cpp
src/logic/ScriptEngine.h
src/target/REGoth.cpp

Added new console command `tp <npc name>`.
The Player will be teleported to the location of the target (if any match is found). The Player will be placed in front of the target and rotated to look towards it.
The npc name given is checked to be part of either the DisplayName or the DATFileName of all NPCs in the current World. The Comparison is case insensitive and all non alpha-numeric character are stripped of all strings beforehand.
Examples: 
- Diego (PC_THIEF); valid names: diego, dieg, iEgo, DIEGO
- Cor Kalom (GUR_1201_CORKALOM); valid names: cor kalom, orka, COR K, GUR1201, 1201cork
I have integrated this name matching also into `knockout` and kill `command`.

Added Console command tp <npc name>. Improved name matching for kill/knockout/tp

---

src/logic/Controller.h
src/logic/DialogManager.cpp
src/logic/DialogManager.h
src/logic/MobController.cpp
src/logic/MobController.h
src/logic/PlayerController.cpp
src/logic/PlayerController.h
src/logic/messages/EventManager.cpp
src/logic/messages/EventManager.h
src/logic/messages/EventMessage.h

Refactored EventManager. Now stores` vector<shared_ptr<EventMessage>>` instead of `vector<EventMessage*>`.
That means it's now safe to use the newly added return value of `EventManager::onMessage` https://github.com/REGoth-project/REGoth/blob/SharedPointerMessages/src/logic/messages/EventManager.h#L22
The Message might not be in the queue any longer but it may still be referenced. So it's always safe to store shared pointers to the Messages outside of the Eventmanager class.
Also fixed some `reinterpret_cast` to `dynamic_pointer_cast`

reworked EventMessage pointers to shared pointers

---

src/audio/AudioWorld.cpp
src/content/Sky.cpp
src/content/Sky.h
src/engine/BaseEngine.cpp
src/engine/BaseEngine.h
src/engine/GameEngine.cpp
src/engine/GameEngine.h
src/engine/World.cpp
src/engine/World.h
src/logic/NpcScriptState.cpp
src/logic/PlayerController.h
src/logic/scriptExternals/Externals.cpp
src/target/REGoth.cpp
src/ui/Hud.cpp
src/ui/Hud.h

- Added day Indicator besides clock
- game time starts at Day 1 8:00
- Day adjusts when clock passes 24:00 through frameupdate (not via `set clock`)
- ~new command: `nextday` increments the day (maybe superfluous?)~ command got removed
- renamed `set time` to `set clock`
- new comand `set day`
- new command `set clockspeed` (default=7.0). Value of 1.0 would be normal gothic clock. Speeds up the ingame clock. (affects TA states, routines, sky)
- new awesome command `set gamespeed` (default=1.0). Modifies the updating of all world instances. I.e. Slow motion or super speed for EVERYTHING. Animations, movement, clock, sky, camera, sound (including pitch).
- sky uses World's gametime
- added missing sky transition (7->0)
- implemented external `wld_getday`. Whistler will now be very angry if …

Added Day support, Day display, external wld_getday

---

src/ui/SubtitleBox.cpp
src/ui/SubtitleBox.h
src/ui/zFont.cpp
src/ui/zFont.h

- text longer no longer out of box
- all lines are centered
- added small space above box
- added (hardcoded) flag to toggle between center/left (=previous) alignment

Subtitle box small adjustments

---

src/audio/AudioWorld.cpp

- fixed compile errors, when compiling without `RE_USE_SOUND` (i.e. android target)

fixed compile errors when compiling with sound disabled

---

src/audio/AudioWorld.cpp
src/logic/DialogManager.cpp
src/logic/DialogManager.h
src/logic/PfxManager.cpp
src/logic/ScriptEngine.cpp
src/logic/ScriptEngine.h
src/logic/scriptExternals/Externals.cpp
src/ui/Menu.cpp

- This is step 1 of a refactoring process of the externals.
- step 2 will be gathering all signatures for all 333 externals ([WoG](https://www.worldofgothic.de/dl/index.php?go=g2functions)) and merging the parameter names from the externals.d into it. -> **new externals specification file**
- step 3 might be flagging certain int variables in the specification file like npc symbol indices.
- step 4 auto generating externals similiar to the current stubs from the specification file. Each registered function (lambda) will call a c++ function with the same name as the external. Signatures of those c++ functions can differ (take handles instead of script-indices). For some variables like npc symbol indices the respective engine handles will be created (i.e. NpcHandle). The c++ function will …

Gathered all externals from Zenlib into Externals.cpp

---

CMakeLists.txt
src/components/AnimHandler.cpp
src/engine/Platform.cpp
src/engine/PlatformGLFW.cpp
src/render/RenderSystem.cpp
src/ui/Hud.cpp
src/ui/View.cpp
src/ui/zFont.cpp

~~**NOT ready to merge yet.**~~
~~I will look into why the windows build failed.~~
Ready to merge
This branch fixes an issue, where bgfx source files are compiled and linked twice.
This causes a linker error in some older gcc versions (i.e. 5.4).

Bgfx re add and update

---

src/content/Sky.cpp
src/engine/GameClock.cpp
src/engine/GameClock.h
src/engine/PlatformGLFW.cpp
src/logic/Inventory.cpp
src/logic/PlayerController.cpp
src/logic/ScriptEngine.cpp
src/logic/ScriptEngine.h
src/logic/scriptExternals/Externals.cpp
src/target/REGoth.cpp
src/ui/Console.cpp
src/ui/Console.h
src/ui/ConsoleBox.cpp
src/ui/ConsoleBox.h
src/ui/Hud.cpp
src/ui/SubtitleBox.cpp
src/ui/zFont.cpp
src/utils/Utils.cpp
src/utils/Utils.h

- Added auto complete for console (F10): `TAB key`
- auto complete acts on all words (since there is no cursor)
- auto complete works on both commands and arguments
- `TAB` also displays a suggestion list, ~~which is currently showed in the Terminal (from which the program was started)~~ Suggestion list is now working and triggered on each character added.
- If a command is entered, all checks are caseinsensitive. (Though the case is still preserved/corrected by auto complete, to give a better feedback)
- new command `removeitem`. Removes items from player's inventory.
- `giveitem` / `removeitem` now searches in Datfile-Names (=gothic insert codes), `description` (=Inventory Name) and `name` =(name when on ground)
- `tp` command now supports teleporting npc A to npc B via `tp A B`, `A` is …

Console auto complete + tp, kill, knockout, giveitem, removeitem rework

---

src/logic/DialogManager.cpp
src/logic/DialogManager.h
src/logic/scriptExternals/Externals.cpp
src/math/mathlib.h
src/target/REGoth.cpp
src/ui/Console.cpp
src/ui/Console.h
src/ui/ConsoleBox.cpp
src/ui/ConsoleBox.h
src/ui/DialogBox.cpp
src/ui/Menu_Main.cpp
src/ui/Menu_Status.cpp
src/ui/View.h
src/utils/Utils.cpp
src/utils/Utils.h

- Auto-complete rework:
- Navigation through suggestions via: `PAGE_UP`, `PAGE_DOWN`, `HOME`, `END`
- auto-complete no longer works on all tokens simultaneously (now: only the last/next)
- `TAB` inserts currently selected entry
- Sorting of suggestions improved a bit
- Console now demands exact case. (to distinguish between `WOLF` (`Wolf`) and `Wolf` (`ORG_855_WOLF`) )
- No more duplicate suggestions
- Changed the behavior of the externals `Info_AddChoice` and `Info_ClearChoices` to match the exact same behavior as in the original game. Though there should be no observable change compared to master branch. Sub-choices are now associated to the corresponding `C_Info` and survive the end of the Dialog (like in the original, though this behavior is never used).

Autocomplete Rework (select suggestion) & Internal Dialog rework

---

src/engine/BaseEngine.cpp
src/engine/BaseEngine.h
src/engine/Input.h
src/engine/PlatformGLFW.cpp
src/logic/DialogManager.cpp
src/logic/DialogManager.h
src/logic/PlayerController.cpp
src/logic/SavegameManager.cpp
src/logic/SavegameManager.h
src/target/REGoth.cpp
src/ui/Console.cpp
src/ui/Console.h
src/ui/Hud.cpp
src/ui/Menu.cpp
src/ui/Menu.h
src/ui/Menu_Load.cpp
src/ui/Menu_Load.h
src/ui/Menu_Main.cpp
src/ui/Menu_Main.h
src/ui/Menu_Save.cpp
src/ui/Menu_Save.h
src/ui/Menu_Status.cpp
src/ui/Menu_Status.h
src/ui/View.h
src/utils/Utils.cpp
src/utils/Utils.h

- fixed lots of issues with savegame slots. Different number of save game slots in gothic 1/gothic 2 (15/20+1) should now be handled correctly.
- implemented quicksave/quickload (F5/F9) functionalities for G1+G2.
- G1 does not have a visible quicksave slot in the loading menu (this could be fixed by extending the scripts like G2 does). Loading in G1 is therefore only possible via console (quicksave is slot 0) or hotkey (F9).
- fixed player moving around while saving via menu. #164 .  (@degenerated1123  Bindings no longer fire when a menu is open).
- console is no longer hidden, when the hud is hidden via the console command `hud`

Save game fix

---

src/audio/AudioWorld.cpp
src/content/Sky.cpp
src/engine/World.cpp
src/engine/World.h
src/logic/DialogManager.cpp
src/logic/NpcScriptState.cpp
src/logic/NpcScriptState.h
src/logic/PfxManager.cpp
src/logic/PlayerController.cpp
src/logic/SavegameManager.cpp
src/logic/SavegameManager.h
src/logic/ScriptEngine.cpp
src/logic/scriptExternals/Externals.cpp
src/logic/scriptExternals/Externals.h
src/ui/Menu.cpp

- implemented external `Npc_SetStateTime`. In example: Vatras will now make a short pause between his preaches
- Zenlib: added and registered all missing (Gothic-2-only-)data members of engine classes (C_Classes).
- Zenlib: fixed invalid member registering for the wrong VMs (Particle, Menu, Gothic). Menu classes no longer registered in non Menu-VMs and vice versa.
- Zenlib: fixed incorrect registering of aivar array. This means script functions using the aivar array should work now. In example the Lefty-water quest can now be completed. (though Lefty still is on invalid position and must be teleported to the hero via `tp Lefty PC_HERO`). Also Vatras now tells the full story instead of the first talk over and over again. TODO: Fix: Vatras' monolog interferes with the player's dialog.
- …

Npc set state time + Zenlib fixes

---

src/engine/Input.cpp
src/engine/Input.h
src/target/REGoth.cpp
src/ui/Console.cpp
src/ui/Console.h
src/ui/ConsoleBox.cpp

- press `TAB` to show suggestions (when none are available)
- if only one suggestion is found it is inserted directly
- Press or hold `TAB`/ `SHIFT` + `TAB` to cycle through suggestions forwards/backwards. (Page up/down, home/end keys still work)
- selecting suggestion will now always insert the value from column 1 (=Scriptname for items/npcs) instead of the best match column.
- choose selection with `ENTER`
- submit command with `ENTER` (when nothing is selected)
- changed sorting of suggestions (again). Suggestions are sorted lexicographically by scriptnames. (but candidates that start with the given string are still first)
- reworked key repeat to use the default GLFW behaviour. Added modifers (i.e. `SHIFT`). Time until key repetition and in between repetition is now smaller.

Improved Console Suggestion ordering and selecting + navigation

---

src/logic/DialogManager.cpp
src/logic/ScriptEngine.cpp
src/logic/ScriptEngine.h
src/logic/scriptExternals/Externals.cpp
src/logic/scriptExternals/Stubs.cpp
src/target/REGoth.cpp

- printing the VM's callstack now actually works (script functions, externals, arbitrary depth)
- fixed many superfluous pushes to the data stack (`pushint(0)`), since the VM already pops 0 by default
- script function calls from engine (outermost call): VM now only pop's a value if the function has a return flag (specifed in DAT-file).
- VM now complains about missing return values on the stack (i.e. happens on many  dialog conditions: DIA_..._CONDITION)
- fixed some externals that messed up the stack.
- VM's stack gets cleared before engine calls a script function (outermost call)

Daedalus vm debug features

---

src/logic/PlayerController.cpp

Regarding Dialogs (Monologs), where speaker=target (Vatras, Herold)
- Monologs no longer display are SubtitleBox
- no longer incorrect canceling of Monologs, when player trys to cancel Dialog Talk.

fixed Preach/Announcement Monologs interfering with Dialogs

---

CMakeLists.txt
src/android/CMakeLists.txt

Implement function to automatically get submodules when running cmake.
Also remove trailing whitespaces and replace some tabs lost among the spaces.

Automatically get submodules with cmake

---

src/ui/Hud.cpp

It was possible to open up the main menu and start another world.

Prevent input while loading screen is visible

---

src/logic/DialogManager.cpp
src/logic/DialogManager.h
src/logic/PlayerController.cpp
src/logic/messages/EventMessage.h
src/logic/scriptExternals/Externals.cpp
src/logic/scriptExternals/Stubs.cpp

Dialog manager rework.
- fixes #213 
- Instead of starting `ZS_Talk`, `B_AssessTalk` is called, which handles all the checks/pre-dialog stuff.
- Monsters no longer get aligned to the player when trying to talk to them.
- "Not Now" voiceline is now functioning (handled by `B_AssessTalk`) when trying to start a dialog as controlled NPC .
- implemented external `Npc_CheckInfo`
- rudimentary implementation for `Wld_GetGuildAttitude`

Dialog fixes

---

.clang-format
CMakeLists.txt
cmake/clang-format.cmake
create_git_hooks.sh
hooks/pre-commit

This pull requests adds a make target that can be used for formatting every source file with:
`make clang-format`
Additionally I added a git pre-commit hook that runs clang-format on added/changed git files and a simple bash script that symlinks the hook to `.git/hooks/*`
Rational: #79

Clang format

---

CMakeLists.txt
src/engine/PlatformGLFW.cpp

including utils/Utils.h pulled in HandleDef.h containing the Handle namespace.
glfw3native.h includes some macos headers though, which #define Handle.
As PlatformGLFW does not really need the entirety of utils/Utils.h I just forward declared the one function that is actually called.
This makes REGoth compilable on MacOS.
I still need to fix runtime issues though, but these fixes may happen in following pull requests :)

allow building on/for macos

---

src/logic/Console.cpp
src/utils/naturalcompare.h

- strings containing numbers are now sorted more naturally. i.e. the Castle waypoints in G1

changed sorting of console suggestions to natural sort

---

src/content/AnimationLibrary.cpp

loadAnimations crashed when iterating over a file/directory("SFX" in
Gothic 2) with a name shorter than 4 characters.

Fix animation loader crash

---

src/engine/GameSession.h
src/engine/World.cpp
src/engine/World.h
src/logic/LogManager.cpp
src/logic/LogManager.h
src/logic/SavegameManager.cpp
src/logic/scriptExternals/Externals.cpp
src/ui/MenuItemListbox.cpp
src/ui/MenuItemListbox.h
src/ui/MenuItemListboxEntry.cpp
src/ui/MenuItemListboxEntry.h
src/ui/Menu_Log.cpp

- now keep mission-/note log on world switch (moving `LogManager` from `GameState` to `GameSession`)
- code refactoring

Log tweaks

---

src/components/Entities.h
src/components/EntityActions.cpp
src/components/EntityActions.h
src/components/Vob.cpp
src/content/ContentLoad.cpp
src/engine/World.cpp
src/engine/World.h
src/logic/CameraController.cpp
src/logic/NpcAIHandler.cpp
src/logic/NpcAIHandler.h
src/logic/NpcScriptState.cpp
src/logic/Pathfinder.cpp
src/logic/Pathfinder.h
src/logic/PlayerController.cpp
src/logic/PlayerController.h
src/logic/messages/EventManager.cpp
src/logic/messages/EventMessage.h
src/logic/scriptExternals/Externals.cpp
src/logic/visuals/ModelVisual.cpp
src/logic/visuals/StaticMeshVisual.cpp
src/render/RenderSystem.cpp
src/render/RenderSystem.h

- Npcs now move using their animations. This also means they do the "start-running" and "stop-running" animations.
- Npcs could now draw weapons and fight, but there isn't any code triggering that at the moment.
- Pathfinding was improved. Walking towards moving targets has been improved as well. 
- Npcs can now go to arbitrary positions, thus, moving to freepoints has been implemented and following someone has been improved (Think Mud!)
- Argument `--show-routes` has been added for debuggung
- Some misc sound fixes and improvements
- World now actually runs destruct-functions of components
- Event-Messages now have a "isFirstRun"-flag

Npc movement

---

src/engine/PlatformGLFW.cpp

this happens for example on macos with retina displays where screen units don't necessarily map to pixels 1:1

fix for game only showing in the lower left corner of the window

---

src/components/AnimHandler.cpp
src/engine/GameEngine.cpp
src/logic/CameraController.cpp
src/logic/CameraController.h
src/logic/NpcAIHandler.cpp
src/logic/PlayerController.cpp
src/target/REGoth.cpp
src/target/REGoth.h

> You can move the free camera to a location, put a keyframe there, move it to a different location, put another keyframe and then have it interpolate between those positions.
There are 3 commands, kept short since you need to type them often:
kf - put keyframe
ckf - clear all keyframes
pkf <duration> - play keyframes (interpolate between all keyframes)
Improves the `hud` console command, so you can turn off the Debug-Text on the upper left corner.
Adds `-rdist` flag for controlling the render-distance

Camera animation

---

src/components/VobClasses.cpp
src/engine/BaseEngine.cpp
src/engine/GameSession.cpp
src/engine/GameSession.h
src/engine/Input.cpp
src/engine/Input.h
src/engine/PlatformGLFW.cpp
src/engine/World.cpp
src/engine/World.h
src/logic/CameraController.cpp
src/logic/CameraController.h
src/logic/Controller.cpp
src/logic/Controller.h
src/logic/MobController.cpp
src/logic/NpcAIHandler.cpp
src/logic/NpcAIHandler.h
src/logic/PlayerController.cpp
src/logic/PlayerController.h
src/logic/SavegameManager.cpp
src/math/mathlib.cpp
src/math/mathlib.h
src/target/REGoth.cpp
src/utils/Utils.cpp
src/utils/Utils.h

- added mouse control for Third Person Camera (x/y-axis + mousewheel zoom)
- Moved the registering of the bindings out of the PlayerController.
- Camera Hotkeys F1-F4 should work again now

fixed camera Keybindings + Third Person Camera Mouse control

---

src/engine/World.cpp

Checking whether an entity has been deleted before actually deleting it

---

src/logic/NpcAnimationHandler.cpp
src/logic/NpcAnimationHandler.h

Goblins use the "fist"-modes like all other monsters, even though they are holding a 1h-weapon.
Maybe someone can come up with a nicer solution than this when we completely figured that one out.

Anim: Workaround for goblins using the wrong animation-set

---

.travis.yml
.travis_build.sh

It is possible to configure Travis to upload artifacts to every tag, but it requires GITHUB_OAUTH token, so I couldn't do that: https://docs.travis-ci.com/user/deployment/releases/

Configure MacOS travis build

---

src/components/AnimHandler.cpp
src/logic/NpcAnimationHandler.cpp
src/logic/NpcAnimationHandler.h

Reworked `NpcAnimationHandler`.
- Walking now works in G2, too
- Other walkmodes (Walk, Swim, Dive, Sneak) are available and functional
- Overall animation handling is now less rigid than before
Also fixes Dialogs not startable in G2, caused by NPCs being stuck in an invalid animation state due to the `S_WALK` animation missing. (Issue #287 )

Walkmode g2 fix

---

src/engine/World.cpp
src/logic/DialogManager.cpp

The state of the scriptengine (global vars) is now imported before `init_<worldname>()` is run.
fixes #280

fixed init_world script-fu run before script engine import

---

create_git_hooks.sh
hooks/pre-commit

- the bash script `create_git_hooks.sh` will now work properly and creates the git hook.
- Replaced the pre-commit hook with a new version
- you got 3 choices:
- yes: apply formatting & commit
- no: commit without formatting
- abort: abort commit
This is what it looks like now:
```
$git commit 
The following files do not match the clang-format rules:
src/target/REGoth.cpp
Differences:
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
--- a/src/target/REGoth.cpp	2017-10-20 21:15:00.442098201 +0200
+++ b/src/target/REGoth.cpp	2017-10-20 21:15:07.622936504 +0200
@@ -294,7 +294,7 @@
});
console.registerCommand("foobar", [this](const std::vector<std::string>& args) -> std::string {
-    return "foobar!";
+        return "foobar!";
}); …
```

fixed incorrect creation of symlink for pre-commit hook

---

REGoth-Android/app/src/main/AndroidManifest.xml
REGoth-Android/app/src/main/res/values/styles.xml
src/engine/PlatformAndroid.cpp

On some devices both events AINPUT_SOURCE_TOUCHSCREEN & AINPUT_SOURCE_STYLUS are triggered on tap/touch.
see https://github.com/SFML/SFML/issues/953 for more details

Fix for #298: [Android] Taps are not recognized + Hide ActionBar in fullscreen mode

---

CMakeLists.txt

I am using some ubuntu 18 based distro, which offers gcc 5.4 in the package manager (I guess ubuntu 18 uses the same version).
When I joined this project, I fixed some link time issues, that caused the build to fail with gcc 5.4.
Since then I have been using gcc 5.4 without problems, so I think we can lower the required gcc version.

Lowered Required GCC Warning 6.0 -> 5.4

---

src/physics/PhysicsSystem.cpp
src/physics/PhysicsSystem.h

Fixes leaking of `btStridingMeshInterface`.
`PhysicsSystem::makeConvexCollisionShapeFromMesh` would still leak, but is not used atm.
fixes #296

Fix Bullet memory leaks

---

src/logic/PfxManager.cpp
src/logic/PfxManager.h
src/logic/visuals/PfxVisual.cpp
src/math/mathlib.h

Implementes soft alpha fade for particles in G2.
Whether soft-alpha should be active is encoded inside the `visTexAniIsLooping` flag as a value of `2`. 
Fixes #273.

Pfx soft alpha

---

src/target/REGoth.cpp

I forgot to take out some logging a while ago, which would cause windows builds to take like 5 minutes to start up due to stdout being so slow...

Removed log-spam, which slowed down windows startup times

---

src/content/AnimationAllocator.h
src/logic/Console.cpp
src/logic/Console.h
src/target/REGoth.cpp

- the `playanimation` command now has autocomplete.
- it is possible to play the animation on specified target npc (default is player)
PS:
I'm not sure if it would be better to expose `std::map<std::string, Handle::AnimationHandle> m_AnimationsByName;` as `const reference` instead of returning a copy of the strings.

Autocompletion for playanimation console command

---

src/logic/scriptExternals/Externals.cpp
src/logic/scriptExternals/Stubs.cpp
src/ui/Hud.cpp
src/ui/Hud.h
src/ui/IntroduceChapterView.cpp
src/ui/IntroduceChapterView.h

See Issue #338 
This might be better fit as some kind of menu, but there is not scriptdata for chapter notifications as far as I can tell.
So because it is just a view, handling input (closing the notification early) and pausing the engine might not be the ideal way to go about it.
Playing the sound is also a little convoluted. For now its good enough, but it should be changed once the audio system gets reworked to include a way to play sounds independently of the World.
You could use OpenAL directly, but I dont think that is very elegant.

Implement Chapter Notification

---

src/logic/CameraController.cpp
src/logic/CameraController.h
src/logic/DialogManager.cpp
src/logic/PlayerController.cpp

This is a clean version of #357 
Defined camera transformations (shot types) and a state machine to decide between them during dialogs with NPCs.
There are 4 shot types:
- Full shot
- Over the shoulder shot
- Neutral shot
- Close up shot
In order to keep shot progression feeling natural, Full and Over the shoulder shots
should be used a couple times before opening up the chance to move on to Neutral and Close Up
shots. Furthermore, the camera should only push further in and not back out once it progressed
to at least a Neutral shot.
Dialog shot progression therefore respects the following rules:
- Always start with either a Full or Over the shoulder shot
- Close up and Neutral shot can only be used after Full or Over the shoulder have been used at least as often as …

Implemented basic dialog camera
