src/engine/World.cpp
src/utils/Utils.cpp
src/utils/Utils.h

Case sensitive path merge and remove getFirstCaseSensitiveChar

---

src/target/REGoth.cpp

That's just it - felt a little lack of it. (first commit 😄 !)

Added simple command to shutdown the game.

---

src/engine/Platform.cpp
src/engine/Platform.h
src/engine/PlatformAndroid.cpp
src/engine/PlatformGLFW.cpp
src/engine/PlatformGLFW.h
src/engine/World.cpp
src/engine/World.h
src/target/REGoth.cpp

What the title says, also adds shutdown via a quit flag instead of just calling exit(0)

Some shutdown-related fixes

---

src/logic/scriptExternals/Externals.cpp
src/logic/scriptExternals/Stubs.cpp

Called often spamming the log. ;)

Implemented wld_istime

---

src/content/Sky.cpp
src/content/Sky.h
src/target/REGoth.cpp
src/ui/Console.cpp
src/ui/Console.h

Fixed sky timing, implemented multiword console commands, added "set time" command

Kaffeine, Console, Sky/time.

---

src/engine/BaseEngine.cpp
src/engine/World.cpp
src/engine/World.h
src/logic/DialogManager.cpp
src/logic/DialogManager.h
src/logic/PlayerController.cpp
src/target/REGoth.cpp
src/ui/Menu_Load.cpp

Quick fix for segmentation fault when path to game files is not provided on startup and removal of extensive logging when surface materials are not recognized.

Small fixes

---

CMakeLists.txt
src/audio/WavReader.cpp
src/logic/CameraController.cpp
src/logic/MobController.cpp
src/logic/NpcScriptState.cpp
src/logic/PlayerController.cpp
src/logic/messages/EventMessage.h
src/logic/scriptExternals/Externals.cpp
src/logic/visuals/ModelVisual.cpp
src/ui/DialogBox.cpp
src/ui/Menu.cpp
src/ui/Menu_Load.cpp
src/ui/Menu_Save.cpp
src/ui/SubtitleBox.cpp
src/ui/View.cpp
src/ui/zFont.cpp
src/utils/Utils.cpp

Fixed up some of the warnings, added -Wall and -Wextra to compilation flags and disabled optimizations based on strict aliasing due to numerous violations and usage of O2 optimization.

Warning fixes

---

README.md

I hope with it I'll rehabilitate creating non existing error.

Fix wiki link.

---

src/logic/PlayerController.cpp

Just a small one-liner because I was bored =)

correctly set StrafeLeft animation when pressing A to fix #69

---

src/components/AnimHandler.cpp
src/math/mathlib.h

Soft interpolation between animation frames. Especially noticeable on the idle-swimming-animation.

Animinterp

---

src/engine/WorldMesh.cpp
src/engine/WorldMesh.h
src/logic/PlayerController.cpp
src/logic/PlayerController.h
src/logic/visuals/StaticMeshVisual.cpp
src/physics/PhysicsSystem.cpp
src/physics/PhysicsSystem.h

Added a new version of raytrace which returns all results.
Implemented smooth walk->swim transition

Implemented Multi-Raytrace and smooth walk-swim transition

---

src/engine/Input.cpp
src/engine/Input.h
src/engine/PlatformGLFW.cpp
src/engine/PlatformGLFW.h
src/target/REGoth.cpp
src/ui/Console.cpp
src/ui/Console.h
src/ui/Hud.cpp
src/ui/Hud.h
src/ui/Menu.cpp
src/ui/Menu.h

Resolves issues with non US-Keyboard layouts, also allows to type more special characters and upper/lowercase.

Input: Implemented proper text input

---

src/logic/PlayerController.cpp
src/logic/PlayerController.h

Ok, I think i fixed the issue.

Fix #44 Don't update animation when menu is active

---

src/logic/PlayerController.cpp
src/logic/PlayerController.h
src/logic/visuals/ModelVisual.cpp
src/logic/visuals/ModelVisual.h

Commit description pretty much explains the whole change ;-)

Added wade support for shallow water

---

src/target/REGoth.cpp
src/ui/Menu.h
src/ui/Menu_Save.cpp
src/ui/Menu_Save.h
src/ui/View.h

I gave it a shot. 
There is an issue with B key, because it brings up the status menu on top of other menus.

Add nameable save games

---

src/logic/Inventory.cpp

fixed issue where game always removed 1 item from the inventory instead of the specified amount

fixed missing forwarding of item count, when removing items

---

src/logic/DialogManager.cpp
src/logic/PlayerController.cpp
src/logic/messages/EventManager.cpp
src/logic/messages/EventManager.h
src/logic/messages/EventMessage.h

see issue: #107 
not ready to merge yet

Conversation wait fix

---

src/logic/PlayerController.cpp
src/target/REGoth.cpp

Not sure where those merge-commits come from, but this PR fixes:
- Holding Backspace not working in Console
- NPCs popping up and down for some animations
- Unnecessary delay between statechange and message processing

Various fixes

---

src/logic/DialogManager.cpp
src/logic/DialogManager.h
src/logic/PlayerController.cpp
src/logic/messages/EventManager.cpp
src/logic/messages/EventMessage.h
src/math/mathlib.h
src/target/REGoth.cpp
src/ui/DialogBox.cpp
src/ui/SubtitleBox.cpp
src/ui/SubtitleBox.h

- npc won't start their dailyroutine while player has last message (i.e. farewell: diego, mordrag ...)
- moved conversation callback code into playercontroller
- SubtitleBox grows/shrinks now. Sound overlaps with growing. Cancel will cause shrink at any time.

Subtitle box grow shrink. Farewell fix

---

src/logic/ScriptEngine.cpp
src/target/REGoth.cpp

I have added a giveore command. It comes with Bloodwyn's approval.

Add giveitem console command

---

src/logic/PlayerController.cpp
src/logic/PlayerController.h
src/logic/SavegameManager.cpp
src/logic/SavegameManager.h
src/target/REGoth.cpp
src/ui/Menu_Save.cpp

This shoud fix #163 
But with this solution we might run into problems with mods as they shoud have their owm savegames aswell.

Seperated G1 and G2 savegame folder

---

src/engine/BaseEngine.cpp
src/engine/BaseEngine.h
src/engine/Input.h
src/engine/PlatformGLFW.cpp
src/logic/DialogManager.cpp
src/logic/DialogManager.h
src/logic/PlayerController.cpp
src/logic/SavegameManager.cpp
src/logic/SavegameManager.h
src/target/REGoth.cpp
src/target/REGoth.cpp.orig
src/ui/Console.cpp
src/ui/Console.h
src/ui/Hud.cpp
src/ui/Menu.cpp
src/ui/Menu.h
src/ui/Menu_Load.cpp
src/ui/Menu_Load.h
src/ui/Menu_Main.cpp
src/ui/Menu_Main.h
src/ui/Menu_Save.cpp
src/ui/Menu_Save.h
src/ui/Menu_Status.cpp
src/ui/Menu_Status.h
src/ui/View.h
src/utils/Utils.cpp
src/utils/Utils.h

- dialogs with ambient npcs should work now. fixes #120 
(this branch was branched from SaveGameFix)

Ambient npc dialog

---

src/logic/DialogManager.cpp
src/logic/DialogManager.h
src/logic/scriptExternals/Externals.cpp
src/logic/scriptExternals/Stubs.cpp

fixes #128 
C_Infos were reversed by Zenlib.

Dialog important info order fix

---

src/logic/visuals/PfxVisual.cpp

@degenerated1123 do I need synchronization here?
In other words: Do I need to wait until the job is finished by the master thread _or_ is queuing sufficient?
fixes #201

added missing bgfx call for particles

---

src/logic/DialogManager.cpp
src/logic/PlayerController.cpp
src/logic/messages/EventMessage.h
src/logic/scriptExternals/Externals.cpp

Implemented `AI_OutputSVM`.
`AI_OutputSVM` is used for the following voice-dependent sayings:
- "tell me the way to ..."
- every non-dialog saying i.e. smalltalk

implemented external AI_OutputSVM

---

src/content/AnimationLibrary.cpp
src/engine/BaseEngine.cpp
src/engine/World.cpp
src/utils/zTools.cpp

This PR updates ZenLib to the last version and tweaks the code to use PhysFS as the VDFS implementation.

PhysFS back-end port

---

src/engine/AsyncAction.h
src/engine/BaseEngine.cpp
src/engine/BaseEngine.h
src/engine/World.cpp
src/logic/PlayerController.cpp
src/logic/SavegameManager.cpp
src/logic/SavegameManager.h
src/target/REGoth.cpp

Listener orientation & --skipmenu flag

---

src/logic/scriptExternals/Externals.cpp
src/target/REGoth.cpp

- new command `insertnpc <npc> <waypoint>`
- updated Zenlib

Insert npc command

---

src/engine/World.cpp
src/engine/World.h
src/logic/ScriptEngine.cpp
src/logic/scriptExternals/Externals.cpp

`WLD_InsertNPC` is able to insert to freepoints now as well
Fixes the issue in #129  (Pepes wolfs)

Npc insert freepoints

---

src/target/REGoth.cpp
src/target/REGoth.h

removed lefovers from bgfx example.

removed bgfx ExampleCube leftovers

---

src/content/AnimationLibrary.cpp
src/utils/Utils.cpp
src/utils/Utils.h

Added string `replace` function and split on extension functionality for filenames.

More string utils

---

src/logic/PlayerController.cpp
src/logic/PlayerController.h
src/logic/scriptExternals/Externals.cpp

Externals `NPC_GetNearestWP` and `NPC_GetNextWP` now return the correct values. Fixes #143.

Externals: Fixed NPC_GetNearestWP and NPC_GetNextWP

---

src/logic/scriptExternals/Externals.cpp

fixed bug in external `WLD_Istime` when startpoint is endpoint.

fixed WLD_Istime (fixes Monster routines)

---

src/audio/AudioWorld.cpp
src/render/WorldRender.cpp

- Removed log spam on "play sound"
- Removed renderer debug output

Various fixes 2

---

src/engine/Input.cpp
src/engine/PlatformGLFW.cpp
src/logic/PlayerController.cpp

3 bugs fixed
- PlayerAction bindings no longer registered continous
- FireBindings no longer resets Mousebutton-Triggered to early when using multiple bindings to one button
- Fixed evil static bool in `PlayerController:onAction` which causes problems when using multiple bindings

fixed LMB for PlayerAction

---

src/logic/scriptExternals/Externals.cpp

Reduced log warning spam to improve performance on windows.

disabled some VM warnings

---

src/logic/visuals/ModelVisual.cpp

Fixed Body-Textures for Black Goblins and Goblin-Warriors

---

src/engine/GameEngine.h
src/engine/PlatformGLFW.h
src/logic/CameraController.h
src/logic/ItemController.h
src/logic/MobController.h
src/logic/PlayerController.h
src/logic/SoundController.h
src/logic/VisualController.h
src/logic/messages/EventMessage.h
src/logic/mobs/Container.h
src/logic/mobs/Ladder.h
src/logic/visuals/ModelVisual.h
src/logic/visuals/PfxVisual.h
src/logic/visuals/StaticMeshVisual.h
src/physics/DebugDrawer.h
src/physics/MotionState.h
src/physics/PhysicsSystem.cpp
src/ui/Menu_Load.h
src/ui/Menu_Log.h
src/ui/Menu_Main.h
src/ui/Menu_Save.h
src/ui/Menu_Status.h

Virtual functions should specify exactly one of virtual, override, or final.
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rh-override

Apply CppCoreGuideline C.128

---

src/components/Entities.h
src/content/SkeletalMeshAllocator.cpp
src/content/SkeletalMeshAllocator.h
src/content/StaticMeshAllocator.cpp
src/content/StaticMeshAllocator.h
src/engine/GameEngine.cpp
src/logic/Pathfinder.cpp
src/logic/visuals/ModelVisual.cpp
src/logic/visuals/PfxVisual.cpp
src/logic/visuals/PfxVisual.h
src/logic/visuals/StaticMeshVisual.cpp
src/render/RenderSystem.h
src/render/WorldRender.cpp

Implemented frustum-culling for most objects
Performance on Android has been significantly improved. On Desktop, it hardly dips below 300fps now in the old camp for me (before ~80).

Renderer performance

---

src/logic/NpcAIHandler.cpp
src/logic/NpcAIHandler.h
src/logic/NpcAnimationHandler.cpp
src/logic/NpcAnimationHandler.h

Basic fight animations (forward, left, right, parry) for fist/1h/2h. Keys can be released after pressing, like in the original game.

Basic fight animations

---

src/logic/Console.cpp
src/ui/ConsoleBox.cpp
src/utils/naturalcompare.h

Fixed console crash on windows when typing/displaying umlauts

---

src/logic/CameraController.cpp

Camera was pointing too far down, IMO

Camera: Modified camera angle to look further up

---

src/logic/CameraController.cpp
src/target/REGoth.cpp

The command 'playsound' now lists all .wav files as autocomplete options.

Playsound autocomplete

---

bin/build_android.sh
src/content/Texture.cpp
src/engine/BaseEngine.cpp
src/engine/BaseEngine.h
src/render/WorldRender.cpp

Adds runtime flag to disable texture filtering.

---

src/math/mathlib.h

I had almost forgotten about this one!
Adds a bunch of helper constructors and should also remove various warnings

Mathlib improvements
